/*******************

Written by Frank Rimlinger, May 1993
*******************/

#include "crossTrainer.h"
#include "FpLibInitInfo.h"
#include "stdio.h"
#include "FGLvar.h"
#include "FpLib.h"

FpLibInitInfo::FpLibInitInfo(void){

// NAME
	sprintf((char *)errorStr,"pLib"); // designation of GLvar for error handler
	CtoPstr((char *)errorStr);				  // use Pascal version

// WALKS
	IDactiveMax=0;				// number of simultaneously active walks

// PACKET SIZES	
	rNoEntries=5;			// real link of a real vertex 
	iNoEntries=10;			// ideal link of an ideal vertex 			
	lutNoEntries=5;			// ideal vertex look-up table				
	ChildNoEntries=10;		// child vertices generated by FGLwalkNode
	
// DATA
	useD=FALSE;
	DtypeSize=0;
	useiD=FALSE;
	iDtypeSize=0;

	
// RECYCLING
	recycleBlockSize=1064;
	recycleReal=TRUE;
	recycleIdeal=TRUE;
	
// BACKYARDS
	rBackYardSize=0;
	irBackYardSize=0;
	iBackYardSize=0;
	lutBackYardSize=0;
	rvBackYardSize=0;
	ivBackYardSize=0;
}
